# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
# Mod properties
maven_group=es.degrassi
archives_name=custommachinerybotania

minecraft_version=1.20.1
enabled_platforms = fabric,forge
# Minecraft properties

modid=custommachinerybotania
mod_version = 1.2.0
mod_name=Custom Machinery Botania
mod_description = Add Botania integration for Custom Machinery
author = Alec_016GG
homepage = https://www.curseforge.com/minecraft/mc-mods/custom-machinery-botania
github = https://github.com/alec016/CM-Botania
issues = https://github.com/alec016/CM-Botania/issues
wiki = https://alec016.gitbook.io/custom-machinery-botania-1.19/
license = GNU Lesser General Public License v3.0
icon = icon.png

# Dependencies
architectury_api_version=9.1.13
kubejs_version=2001.6.4-build.121
jei_version=15.3.0.4
cloth_config_version=11.1.118
ct_version=14.0.34

botania_version=1.20.1-446
cm_version=0.10.6

fabric_loader_version=0.15.7
fabric_api_version=0.92.0+1.20.1
forge_version=47.2.20

parchment_version=2023.09.03
